const LAB_GUIDES = [
 {id:'bond',prompt:'Use signed face $10m, clean price 98.50 per 100 and signed accrued interest $40k. Calculate clean and dirty value. Double face AND accrued interest for an otherwise identical doubled position, then reverse both signs for a short. Explain the response to a +1 price-point move.',answer:'Clean $9.85m; dirty $9.89m. Doubled: clean $19.70m, dirty $19.78m. Original short: clean −$9.85m, dirty −$9.89m. A +1 price-point move changes clean value by signed face/100: +$100k for the original long and −$100k for its short. Accrued interest is a separate signed position amount; the lab does not automatically scale it.'},
 {id:'pv',prompt:'Discount a single $1m cash flow due in 5 years at 5% annually. Repeat at 0% and 10%, then extend maturity to 10 years at 5%. Explain the direction. This flat-rate example omits credit and other valuation components.',answer:'At 5% for 5 years: $783,526.17. At 0%: $1m. At 10%: $620,921.32. At 5% for 10 years: $613,913.25. Higher positive rates or longer time reduce present value. At negative rates the direction with time can reverse.'},
 {id:'ipv',prompt:'Face +$20m, FO 99.80, independent 99.65, amount tolerance $25k. Compute the signed difference and amount breach. Switch source from current/comparable to stale and then missing; finally reverse the face sign.',answer:'FO $19.96m; independent $19.93m; difference −$30k. Absolute difference exceeds $25k. Stale evidence remains unverified despite computable arithmetic. Missing evidence means no difference can be determined, not zero. A−$20m face produces+$30k. The result is diagnostic, not automatic booking authority. The lab rounds the difference and tolerance to cents before its strictly-greater comparison.'},
 {id:'bridge',prompt:'Long-asset model: raw $10.2m, booked deductions $200k, gross requirement $500k, eligible same-source booked amount $200k. Calculate accounting FV and the pre-aggregation increment. Reduce only the eligible amount to zero. Do not interpret the output as final regulatory AVA.',answer:'Accounting FV=$10m; increment=max(0,500k−200k)=$300k; illustrative bridge value=$9.7m. With eligible amount zero, increment=$500k and bridge=$9.5m while accounting FV stays $10m. An unrelated booked deduction cannot offset this uncertainty. Eligible amount cannot exceed total booked deductions.'},
 {id:'fvh',prompt:'Classify each measurement conditionally: A uses a qualifying unadjusted identical active-market quote accessible at the measurement date. B has no such quote but all significant inputs are observable. C is like B but a significant correlation input is unobservable. State a change in evidence that could change each answer.',answer:'A Level 1; B Level 2; C Level 3. An exchange listing alone is insufficient for A. Loss of observable support for a significant B input can lead to Level 3; credible new support can change C. Neither a hierarchy transfer nor a sophisticated model automatically determines a reserve. This decision aid assumes the evidence and significance assessment have already been performed.'},
 {id:'uncertainty',prompt:'Assume a normal price distribution with mean 100 and standard deviation 0.20, face $10m. Calculate adverse long and short points using approximately 1.28155 (the calculator retains more precision). Double standard deviation. Explain why these are not automatically regulatory AVAs.',answer:'Long point≈99.7437; short point≈100.2563. Original adverse currency distance≈$25,631.03. At standard deviation 0.40 the distance doubles to≈$51,262.06. The assumed probability mass is 90% above the long point and 90% below the short point. Real calibration, accounting offsets and regulatory aggregation are absent.'},
 {id:'capital',prompt:'Use CET 1$1,000m, final AVA $3m, RWA $10,000m. Calculate the new ratio and basis-point reduction. Double only RWA. Keep all other adjustments fixed. This uses a supplied final AVA rather than deriving it.',answer:'CET 1 after=$997m. Ratio 10.00%→9.97%, a 3bp reduction. At RWA $20,000m the ratio is 5.00%→4.985%, a 1.5bp reduction (a two-decimal display rounds 4.985% to 4.99%). AVA changes regulatory capital, not an extra cash payment or automatic accounting journal.'}
];
