/* Original introductory teaching examples. All people, trades and amounts are fictional. */
const STARTER_TERMS = [
 ['Trade','An agreement to buy, sell or exchange something on specified terms. It is an event, not the total amount still held.'],
 ['Instrument','The financial item or contract involved, such as a share, bond or interest-rate swap.'],
 ['Product','A category of instruments with similar features, such as equities, bonds or swaps.'],
 ['Counterparty','The other party to a transaction. If a bank buys a bond from a dealer, that dealer is the trade counterparty. The bond issuer may be a different company.'],
 ['Position','What remains held or owed at a point in time after trades and other changes. Multiple trades can contribute to one position.'],
 ['Book','An internal grouping of positions used to manage and report activity. It is not a physical book or necessarily a separate bank account. The word can have other meanings, so check the local context.'],
 ['Desk','A team responsible for a type of trading activity. A desk may manage several books.'],
 ['Portfolio','A collection of positions considered together. Its boundary depends on the purpose: a person, book, desk, fund or risk analysis.'],
 ['Legal entity','The legally recognised company that owns rights and obligations. Several desks and books may belong to the same legal entity.'],
 ['Front office / FO','The client-facing or trading side of a bank that enters transactions and produces initial marks. Responsibilities vary by institution.'],
 ['Valuation control','An independent function that challenges valuations and their supporting evidence. Exact organisational names vary.'],
 ['Settlement','Completion of agreed delivery and payment. The trade date and settlement date can differ.'],
 ['Asset','Something that provides an economic resource or right. A positive-value claim can be an asset for its holder.'],
 ['Liability','An obligation. A contract can be an asset for one party and a liability for the other.'],
 ['Long / short','In the simple price examples, long means holding a positive exposure; short means an opposite exposure that generally benefits from a price fall. Borrowing, delivery and collateral can also matter for an actual short sale.'],
 ['Mark','The price or value currently used for a position. Marking a position means updating that number.'],
 ['Currency','The unit in which a price or amount is measured, such as USD or INR. Do not add different currencies without an exchange-rate conversion.'],
 ['Face value / principal','For a plain bond, the reference amount the issuer promises to repay at maturity, subject to its terms and ability to pay. It can differ from the bond’s current market value.'],
 ['Coupon','A bond’s interest payment. A 5% annual coupon on $1,000 face is $50 a year before any special conventions.'],
 ['Maturity','The contract’s scheduled end or repayment date.'],
 ['Unrealised P&L','A change in the value of an open position that has not yet been closed out. Accounting recognition and cash receipt are different questions.'],
 ['Realised P&L','Profit or loss associated with completed activity under the chosen accounting convention. In a simple sale example, sale proceeds minus the relevant cost gives realised trading profit, before fees.']
];
const STARTER = [
 {id:1,title:'What are people actually trading?',minutes:6,take:'A financial trade exchanges money, a financial item or promises about future payments.',paragraphs:[
 'You buy a used bicycle for $100. You exchange cash for an item. Tomorrow someone offers $110 for it. The purchase price is still $100, but its possible selling value has changed. This is only an analogy for cost versus current value; bicycles are not financial instruments.',
 'A share is a small ownership interest in a company. A bond is different: it is a borrowing arrangement, usually with interest payments and a promised repayment. A derivative is a contract whose value depends on something else, such as an interest rate, exchange rate or share price. You will meet swaps and options later; you do not need their pricing formulas yet.',
 'A trade records an agreement: who buys or sells, which instrument, how much, at what price, in what currency and when. The other party is the counterparty. Settlement is when the agreed payment and delivery are completed. Agreement and settlement need not happen on the same day.',
 'A bank may trade to meet a customer’s need, manage an existing exposure or pursue an investment/trading strategy. The purpose does not remove the need to record and value the contract correctly.'
 ],example:'A fictional bank buys 10 shares of Company A from Dealer B at $100 per share.\nInstrument: Company A shares\nCounterparty: Dealer B\nQuantity: 10 shares\nAgreed price: $100 per share\nCash price before fees: 10 × $100 = $1,000',connection:'A trade row is a record of the agreement. The counterparty is not automatically the issuer: Company A issued the shares, but Dealer B sold them in this example.',quiz:{q:'In this example, what is the trade?',options:['The agreement to buy 10 shares at $100 each','Every share the bank owns in every company','The bank’s total profit'],correct:0,explain:'The trade is the specific agreement. The bank’s combined holdings and profit are separate concepts.'}},
 {id:2,title:'A trade is an event; a position is what remains',minutes:7,take:'Several trade events can build one position. Position quantity and position value are different numbers.',paragraphs:[
 'Imagine a shopping history and the contents of your cupboard. The history lists events; the cupboard shows what remains. In the same way, a trade log lists purchases and sales, while a position records the holding or exposure at a specified time.',
 'Continue with the bank’s 10 shares. It buys another 5 of the same shares, then sells 4. Ignoring other changes, the resulting position is 10 + 5 − 4 = 11 shares. There are three trades and one combined position in this example.',
 'If each share is now worth $102, the position value is 11 × $102 = $1,122. Eleven is a quantity; 102 is a price per share; 1,122 is a currency amount. Always keep the units attached. Derivatives need different valuation methods: their notional is not automatically their market value.',
 'A positive holding is a simple long position. An opposite exposure is short. A price increase generally helps the long and hurts the short in these simple linear examples. Actual short selling may involve borrowing and delivery obligations; we introduce signed numbers before those mechanics.'
 ],example:'Trade 1: buy 10 shares\nTrade 2: buy 5 shares\nTrade 3: sell 4 shares\nPosition: +11 shares\nCurrent price: $102 per share\nCurrent value: $1,122',connection:'A position table is often derived from trade records, but real systems also need corporate actions, transfers, cancellations and settlement rules. Counting rows is not the same as summing quantities.',quiz:{q:'You buy 8 shares, buy 3 more and sell 2. What remains?',options:['3 shares because there were three trades','9 shares','13 shares'],correct:1,explain:'8 + 3 − 2 = 9 shares. There are three events, but the resulting position is nine.'}},
 {id:3,title:'Where do desks, books and portfolios fit?',minutes:7,take:'Books organise positions; desks organise people and trading activity. A book is not a product, a trade or a separate legal company.',paragraphs:[
 'A large bank needs smaller groups to manage its activity. A desk is a team focused on particular trading work. It may manage several books. A book groups positions and their results. It does not refer to a notebook or necessarily to a bank account.',
 'A legal entity is the company that legally holds the rights and obligations. A portfolio is a collection of positions considered together for some purpose. The same positions may be grouped differently for desk management, accounting, risk or regulatory reporting.',
 'Our simplified map is: legal entity → desk → book → positions. Trade events feed those positions. Actual banks may use more levels or different relationships. In particular, “trading book versus banking book” is also regulatory language; it is not just the name of a trading desk’s internal book.',
 'Suppose one team has a customer-trading book and a hedge book. Moving a position between those books changes the grouping, but does not necessarily create a new transaction with an external party. A system must distinguish a book transfer from an external purchase.'
 ],example:'Fictional Bank Ltd — legal entity\n  Equity trading desk — team\n    Customer book — internal group\n      Company A position: +11 shares\n      Company C position: +20 shares\n    Hedge book — another internal group',connection:'BookId, DeskId and LegalEntityId answer different questions. A mapping error can move the same value to the wrong report without changing the price at all.',quiz:{q:'A desk has two books containing positions in the same bond. Which statement is safest?',options:['Each book must be a separate legal bank','The bond must have two different issuers','The books are groupings; check the entity and purpose separately'],correct:2,explain:'An internal grouping does not establish a separate legal entity or a different instrument.'}},
 {id:4,title:'Price, value, cash and profit are not the same',minutes:8,take:'Buying, owning, valuing and selling are different events. A value can change before any cash is received.',paragraphs:[
 'Use a fresh, simpler example: buy 10 shares at $100 each, for $1,000 before fees. Later the market price is $105. The holding is then worth $1,050. The $50 increase is an unrealised value gain while the holding remains open. Selling all 10 at $105 would produce $1,050 cash proceeds and a simple $50 realised gain before costs.',
 'Cash proceeds are not the same as profit: the original $1,000 cost must be considered. Nor does a rise in estimated value mean cash has appeared in an account. The accounting treatment of gains depends on the instrument and framework; the arithmetic here isolates the basic idea.',
 'An asset is a resource or right; a liability is an obligation. A derivative can have positive value for one party and negative value for the other. Not every contract is an asset for both sides. We use long-asset deductions in later labs and label that assumption.',
 'Percent means “out of 100”. A 5% change on $1,000 is $50. One basis point is 0.01 percentage point: a rate moving from 5.00% to 5.01% rises by 1 basis point. A bond quote of 98.50 per 100 of face means $985 for $1,000 face before accrued interest—not $98.50 for the whole bond holding.'
 ],example:'Quantity: 10 shares\nPurchase price per share: $100\nPurchase cost: $1,000\nCurrent price per share: $105\nCurrent value: $1,050\nSimple unrealised gain: $50',connection:'P&L stands for profit and loss. Store quantity, price, value, cash flows and P&L in different fields. Never infer their units from the number alone.',quiz:{q:'You sell the 10 shares for $1,050 after paying $1,000. Before fees, the profit is…',options:['$1,050','$50','$1,000'],correct:1,explain:'Profit is $1,050 − $1,000 = $50. The $1,050 is sale proceeds, not profit.'}},
 {id:5,title:'Who checks the bank’s numbers?',minutes:7,take:'The team entering trades should not be the only team judging whether its values are supportable.',paragraphs:[
 'The front office, often shortened to FO, is the trading or client-facing side of the bank. It records transactions and produces initial marks. A mark is the price or value being used today. The word does not tell you whether the number is independently supported.',
 'Independent valuation control challenges the evidence behind those marks. Product control, finance, risk, operations and model-risk teams have related responsibilities. Names and boundaries differ by bank, so treat this as a functional map rather than a universal organisation chart.',
 'IPV means Independent Price Verification. Ask: “Can an independent source support the price or model input?” A difference triggers investigation, not automatic proof that one side is wrong. Adjustments change a valuation for a defined reason. Fair Value Hierarchy describes the evidence behind the measurement. Prudent valuation examines uncertainty for regulatory capital.',
 'These questions connect but are not interchangeable. A trade can pass an independent price comparison and still have an exit cost. It can have an uncertain input without a data-processing failure. A job completing successfully does not demonstrate that all records were included or correctly valued.'
 ],example:'Trader / front office: “Our mark is 100.”\nIndependent check: “Comparable evidence says 99.8.”\nInvestigation: “Are time, instrument and price basis aligned?”\nApproved conclusion: correct, adjust, or retain with evidence.\nReporting: show the value, evidence and decisions separately.',connection:'As a developer, you connect contract data, market observations, calculations and approval records. You do not need to be a trader to ask which input, rule or mapping caused a result.',quiz:{q:'What does a successful nightly valuation job prove by itself?',options:['All prices are fair','Every position passed independent verification','The job completed. Its business results still need checking'],correct:2,explain:'Technical success and business correctness are separate. Completeness, evidence and reconciliation controls are still needed.'}},
 {id:6,title:'Read one trade record with confidence',minutes:6,take:'Read the row as a sentence before attempting its calculation.',paragraphs:[
 'Read this fictional record aloud: “At this valuation date, Fictional Bank Ltd’s equity desk has 10 Company A shares in its customer book, marked at $100 per share in USD.” That sentence names the owner, group, instrument, quantity, price, currency and time.',
 'Now ask what is missing. Where did the price come from? Is it a current observation? Are the shares the same class as the quoted instrument? Has the trade been cancelled? Does the position include all trades? A tidy row is not enough without those connections.',
 'Read the explanation and worked example, then try the checkpoint. The glossary defines unfamiliar terms; the labs offer optional numerical practice.',
 'You are ready to begin the main course when you can explain trade versus position, book versus desk, price versus value and value change versus cash. It is fine to revisit this introduction; the later lessons build on these distinctions.'
 ],example:'TradeId: T-001\nInstrument: Company A shares\nBook: EQ-CUSTOMER\nDesk: Equity\nLegal entity: Fictional Bank Ltd\nQuantity: +10 shares\nMark: $100 per share\nCurrency: USD\nValue: 10 × $100 = $1,000',connection:'Fair-value foundations build on these distinctions: contract, position, price, value and evidence.',quiz:{q:'Which question best checks the meaning of a value field?',options:['What units, date, position and source produced it?','How many characters are in its column name?','Is the value positive?'],correct:0,explain:'Units, timing, population and evidence tell you what the number actually represents.'}}
];
for(const pair of STARTER_TERMS){if(!GLOSSARY.some(g=>g[0].toLowerCase()===pair[0].toLowerCase()))GLOSSARY.push(pair);}
GLOSSARY.sort((a,b)=>a[0].localeCompare(b[0]));
