// Generated by scripts/sync-catalog.cjs from paths/*/path.json.
const LEARNING_PATHS = [
  {
    "id": "financial-foundations",
    "title": "Financial foundations",
    "category": "Finance",
    "status": "ready",
    "description": "From your first trade to independent checks, reserves and prudent valuation. Foundation explainers, applied practice and a complete study pack.",
    "level": "Beginner to intermediate",
    "lessons": 24,
    "href": "course.html#explore"
  },
  {
    "id": "agent-harnesses",
    "title": "Agent harnesses",
    "category": "Technology",
    "status": "planned",
    "description": "A future path on the systems that run, constrain and observe agents.",
    "level": "Intermediate",
    "lessons": []
  },
  {
    "id": "ai-agents",
    "title": "AI agents",
    "category": "Technology",
    "status": "planned",
    "description": "A future path on tools, memory, planning and evaluating agents.",
    "level": "Beginner",
    "lessons": []
  }
];
