'use strict';
const $=id=>document.getElementById(id), model=window.EffectivenessLab;
let tasks=[{id:1,title:'Choose one SQL exercise',status:'ready'},{id:2,title:'Attempt the first query',status:'doing'},{id:3,title:'Ask for sample data',status:'blocked'}],nextId=4;
let activeCard={question:$('question').value,answer:$('answer').value},chosenOpening='';
function show(mode){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==mode);document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.mode)));
function compute(){try{if(!['available','buffer','planned','disruption'].every(id=>$(id).validity.valid))throw new Error('Complete the capacity fields with whole numbers in their stated ranges.');const v=model.capacity(Number($('available').value),Number($('buffer').value),Number($('planned').value),Number($('disruption').value));$('capacity-error').textContent='';$('capacity-result').replaceChildren();for(const [title,value] of [['Original capacity',v.available],['Reserved buffer',v.reserve],['Original planning target',v.target],['Capacity after disruption',v.remaining],['Planned work',v.planned],['Shortfall after disruption',v.shortfall]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=title;dd.textContent=value+' min';$('capacity-result').append(dt,dd);}$('task-bar').style.width=(100-Number($('buffer').value))+'%';$('reserve-bar').style.width=$('buffer').value+'%';$('capacity-note').textContent=v.shortfall?'The plan exceeds remaining capacity by '+v.shortfall+' minutes. Reduce scope, renegotiate or move a commitment.':v.overTarget?'The plan fits remaining capacity but uses '+v.overTarget+' minutes of your chosen buffer.':'The plan fits your chosen target. There are '+v.spare+' uncommitted minutes after the disruption.';return v;}catch(e){$('capacity-error').textContent=e.message;return null;}}
$('capacity-form').addEventListener('submit',e=>{e.preventDefault();compute();});$('disrupt').addEventListener('click',()=>{$('disruption').value='90';compute();});$('defer').addEventListener('click',()=>{$('planned').value='180';compute();});
function board(message=''){const n=tasks.filter(t=>['doing','blocked'].includes(t.status)).length,limit=Number($('wip').value);$('board-status').textContent=message||n+' started tasks / limit '+limit+(n>limit?' — review the excess before starting more.':'.');$('board').replaceChildren();for(const status of ['ready','doing','blocked','done']){const lane=document.createElement('section');lane.className='lane';const h=document.createElement('h3');h.textContent=status[0].toUpperCase()+status.slice(1)+' · '+tasks.filter(t=>t.status===status).length;lane.append(h);tasks.filter(t=>t.status===status).forEach(t=>{const card=document.createElement('article');card.className='task-card';const p=document.createElement('p');p.textContent=t.title;const label=document.createElement('label');label.textContent='Status for '+t.title;const select=document.createElement('select');select.id='task-'+t.id;for(const value of ['ready','doing','blocked','done']){const o=document.createElement('option');o.value=value;o.textContent=value[0].toUpperCase()+value.slice(1);o.selected=t.status===value;select.append(o);}select.addEventListener('change',()=>{try{tasks=model.move(tasks,t.id,select.value,Number($('wip').value));board('Moved '+t.title+' to '+select.value+'.');}catch(e){board(e.message);}document.getElementById('task-'+t.id)?.focus();});label.append(select);card.append(p,label);lane.append(card);});$('board').append(lane);}}
$('task-form').addEventListener('submit',e=>{e.preventDefault();const title=$('task-title').value.trim();if(!title){$('board-status').textContent='Enter a concrete action.';return;}if(tasks.length>=50){$('board-status').textContent='This small lab supports up to 50 tasks. Export your experiment before starting another.';return;}tasks.push({id:nextId++,title,status:'ready'});$('task-title').value='';board('Added '+title+' to Ready.');$('task-title').focus();});$('wip').addEventListener('change',()=>{if(!$('wip').validity.valid){$('board-status').textContent='Choose a whole-number limit from 1 to 10.';return;}board();});
function habit(){try{$('habit-result').textContent=model.plan($('cue').value,$('action').value,$('fallback').value);}catch(e){$('habit-result').textContent=e.message;}}$('habit-form').addEventListener('submit',e=>{e.preventDefault();habit();});
$('recall-prompt').textContent=activeCard.question;$('card-form').addEventListener('submit',e=>{e.preventDefault();const candidate={question:$('question').value.trim(),answer:$('answer').value.trim()};if(!candidate.question||!candidate.answer){$('recall-status').textContent='Complete the question and reference answer.';return;}activeCard=candidate;$('recall-prompt').textContent=activeCard.question;$('reference').hidden=true;$('attempt').value='';$('recall-status').textContent='Card ready. Try recalling the idea before revealing.';$('attempt').focus();});$('reveal').addEventListener('click',()=>{$('reference').textContent=activeCard.answer;$('reference').hidden=false;$('recall-status').textContent='Compare your meaning with the reference. What is accurate, missing or needs correction?';});
const feedback={accuse:'This treats an assumption as a fact and uses an absolute. Try naming the missing feedback and its impact, then ask about availability.',avoid:'Silence leaves the deadline and dependency unresolved. You can make a specific request while allowing the other person to explain their constraints.',ask:'This names an observation and a concrete request while offering a chance to negotiate. Next, listen to the reply and confirm a feasible agreement; the opening alone does not resolve the situation.'};document.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{chosenOpening=b.dataset.choice;$('conversation-result').textContent=feedback[chosenOpening];}));
$('export').addEventListener('click',()=>{const capacity=compute();if(!capacity){$('export-status').textContent='Correct the capacity fields before exporting.';return;}const data={format:'notebook-personal-practice-v1',exportedAt:new Date().toISOString(),capacity,review:$('review').value,tasks,wipLimit:$('wip').value,habit:{cue:$('cue').value,action:$('action').value,fallback:$('fallback').value,reflection:$('habit-reflection').value},learning:{...activeCard,attempt:$('attempt').value,reviewDate:$('review-date').value},conversation:{opening:chosenOpening,request:$('request').value}};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='my-practice.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('export-status').textContent='Export requested. Check your browser downloads for my-practice.json.';});
compute();board();habit();show(document.body.dataset.start||'week');
