const fs=require('node:fs'),path=require('node:path');const {root}=require('./manifest.cjs');
const base=path.join(root,'paths/financial-foundations');
// Practice rows contain no quoted commas; fail rather than silently misparse a future CSV.
const csv=fs.readFileSync(path.join(base,'practice/sample-positions.csv'),'utf8');
if(csv.includes('"'))throw Error('Quoted CSV requires a CSV parser before regenerating practice-data.js.');
const lines=csv.trim().split(/\r?\n/);const cols=lines.shift().split(',');
const rows=lines.map(line=>{const values=line.split(',');if(values.length!==cols.length)throw Error('CSV column count mismatch');return Object.fromEntries(cols.map((key,i)=>[key,values[i]]));});
const key=fs.readFileSync(path.join(base,'practice/answers.md'),'utf8').replace(/\r\n/g,'\n');
fs.writeFileSync(path.join(base,'content/practice-data.js'),'// Generated by scripts/sync-finance.cjs.\nconst PRACTICE_ROWS = '+JSON.stringify(rows,null,2)+';\nconst PRACTICE_KEY = '+JSON.stringify(key)+';\n');
for(const file of ['sample-positions.csv','answers.md'])fs.copyFileSync(path.join(base,'practice',file),path.join(root,'practice',file));
console.log('Practice snapshot and legacy download aliases synchronized.');
